api = "0.10"

[buildpack]
id = "heroku/factor"
version = "0.0.1"

# This workaround can be removed once a new Pack release ships that includes:
# https://github.com/buildpacks/pack/pull/2081
[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets.distros]]
name = "ubuntu"
version = "20.04"

[[targets.distros]]
name = "ubuntu"
version = "22.04"

[[targets.distros]]
name = "ubuntu"
version = "24.04"

[[targets]]
os = "linux"
arch = "arm64"

[[targets.distros]]
name = "ubuntu"
version = "24.04"